---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "ui.fullname" . }}
  labels:
    app: crawler
    component: ui
    release: {{ .Release.Name }}
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: crawler
      component: ui
      release: {{ .Release.Name }}
  template:
    metadata:
      name: ui
      annotations:
        prometheus.io/port: "8000"
        prometheus.io/scrape: "true"
      labels:
        app: crawler
        component: ui
        release: {{ .Release.Name }}
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: ui
          ports:
            - containerPort: {{ .Values.service.internalPort }}
              name: ui
          env:
            - name: MONGO
              value: {{  .Values.mongoHost | default "mongodb" }}
            - name: MONGO_PORT
              value: {{  .Values.mongoPort | default "27017" | quote }}
