{
 "title": "crawler_app",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "crawler_pages_parsed",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "crawler_pages_parsed" }
   ]
  },
  {
   "title": "pages generated by ui instances",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(web_pages_served{component=\"ui\",job=\"kubernetes-pods\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "crawler_site_connection_time_bucket",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(crawler_site_connection_time_bucket[5m])) by (le))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "web_page_gen_time_bucket",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(web_page_gen_time_bucket[5m])) by (le))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "crawler_page_parse_time_bucket heat map",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(crawler_page_parse_time_bucket[5m])) by (le))"
    }
   ]
  }
 ]
}