apiVersion: v1
kind: ConfigMap
metadata:
  namespace: logging
  name: fluentd
  labels:
    app: {{ template "fluentd.name" . }}
    chart: {{ template "fluentd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  fluent.conf: |
  <filter  kubernetes.labels.component:ui>
    @type parser
    format json
    key_name log
  </filter>
