---
# RabbitMQ
apiVersion: v1
kind: Service
metadata:
  name: {{ template "rmq.fullname" . }}
  labels:
    app: crawler
    component: rmq
    release: {{ .Release.Name }}
spec:
  ports:
    - name: rmq
      port: 5672
      protocol: TCP
  selector:
    app: crawler
    component: rmq
    release: {{ .Release.Name }}
---

# RabbitMQ Manager
apiVersion: v1
kind: Service
metadata:
  name: {{ template "rmq-management.fullname" . }}
  labels:
    app: crawler
    component: rmq
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - port: 15672
  selector:
    app: crawler
    component: rmq
    release: {{ .Release.Name }}
---